repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.11
    hooks:
      - id: ruff
        args: ["--config", "pyproject.toml"]
      - id: ruff-format
        args: ["--config", "pyproject.toml"]
  
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: uv run mypy
        language: system
        files: \.py$
        args: ["--config-file", "pyproject.toml"]
